### ISSUE TITLE
Bulk rewrite without specifying all specific file names

### ISSUE THREAD

**Issue by kyaustad** [XboxDev/extract-xiso#75] opened 2023-02-09 16:42 UTC
Maybe there is a way to do this I just don't know, but if I have like 20 .iso files in the directory, is there a way to just tell extract-xiso to just rewrite all .iso's in the directory without manually specifying the names?

**Comment by Ernegien** [comment] 2023-02-09 16:45
A simple batch script perhaps?

**Comment by RadWolfie** [comment] 2023-02-09 22:16
I had researched and couldn't find a simple way to make a batch script. So, I had to make a little bit complex solution for XbSymbolDatabaseUnitTest's cache script. Perhaps [this script](https://github.com/Cxbx-Reloaded/XbSymbolDatabase/blob/master/src/test/scripts/_unittest_cache.bat) as an example will help guide you further to make one you want it to do.

**Comment by JayFoxRox** [comment] 2023-08-20 10:41
More or less a duplicate of #84 but as a feature-request.

However, this can be easily automated around extract-xiso and it's not worth it to complicate the codebase.

Closed.

**Closed by JayFoxRox** 2023-08-20 10:41 UTC
